services:
  mt5-wine:
    build:
      context: .
      dockerfile: mt5.dockerfile
    ports:
      - "50319:50319"
      - "60832:60832"
      - "18847:18847"
    restart: "always"
    volumes:
      - ./.mt5:/app/mt5
      - ./config:/app/config
    working_dir: /app
    command: bash config/setup.sh
