services:
  backtest:
    build:
      context: .
      dockerfile: backtest.dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: python src/backtest.py
  mt5-wine:
    build:
      context: .
      dockerfile: mt5.dockerfile
    ports:
      - "50319:50319"
      - "60832:60832"
      - "18847:18847"
    restart: "no"
    tty: true
    command: bash config/setup.sh
