name: Build and Test MT5 Docker Image
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t mt5-wine .
      - name: Test installation and API
        run: |
          # Start service
          docker compose up mt5-wine -d

          # Test if MT5 installed properly
          docker exec quantnautilus-mt5-wine-1 find /root/.wine/drive_c -name "*MetaTrader*" -type d
          docker exec quantnautilus-mt5-wine-1 test -d "/root/.wine/drive_c/Program Files/MetaTrader 5"

          # Test if MT5 API working properly
          docker exec quantnautilus-mt5-wine-1 cat /tmp/test_metatrader5.log
          docker exec quantnautilus-mt5-wine-1 cat /tmp/test_pymt5linux.log

          # Clean up
          docker compose down
